services:

  mongodb:
    image: mongo:latest
    env_file:
      - ../.env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT}/test --quiet
      interval: 3500s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - app-network
    attach: false

  chroma:
    image: chromadb/chroma:1.0.12
    env_file:
      - ../.env
    ports:
      - "${CHROMA_PORT}:${CHROMA_PORT}"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - app-network
    restart: always
    attach: false

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      mongodb:
        condition: service_healthy
      chroma:
        condition: service_started
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  chroma_data:
    driver: local
